import Header from "@/components/Header/Header";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Providers from "@/Redux/Provider";
import ToastContainer from "@/libraries/ToastifyClient";
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Header />

          {children}

          <Footer />
          <ToastContainer />
        </Providers>
      </body>
    </html>
  );
}
